### ISSUE TITLE
angular not loading before sources for karma

### ISSUE THREAD

**Issue by iangregsondev** [fvanwijk/testRunnerConfig#5]
Hi,

Great little library. I have a small issue, and wonder if you can help?

I am currently integrating it with karma (I will need to do wallaby next :-) ). And the problem is that my angular service file is loaded before angular itself. Anyway to control this ? I have my service wrapped in an IIFE. My service reports 

```
       ReferenceError: Can't find variable: angular
```

I am calling the code like so.

```
var testRunnerConfig = require('test-runner-config'),
    files = require('./sharedFiles.js'),
    config = testRunnerConfig.getKarmaFiles(files);
```

I am printing out the config before in my karma file and get the following output, you will see that angular is loading last. tried place it in the src part but that didn't seem to work.

```
{ files: 
   [ '../../../main/javascript/client/**/*.js',
     '**/*.js',
     '../../../../node_modules/angular/angular.js',
     '../../../../node_modules/angular-mocks/angular-mocks.js' ],
  exclude: [] }
```

Here is my file.

```
var nodeModulesPath = '../../../../node_modules/';
var applicationPath = '../../../main/javascript/client/';

module.exports = [
    {
        type: 'lib',
        files: [
            nodeModulesPath + 'angular/angular.js',
            nodeModulesPath + 'angular-mocks/angular-mocks.js'
        ]
    },
    {
        type: 'src',
        files: [
            applicationPath + '**/*.js'
        ]
    },
    {
        type: 'specs',
        files: [
            '**/*.js'
        ]
    }
];
```

**Comment by ianjohnspain** [comment]
Also tried getting wallaby to work, and placed an ignore section. but its trying to run tests on my wallaby-client.js and karma.conf.js - it should ignore these?

> Failing tests
> 
> Error: Cannot find module 'test-runner-config'
> 	at karma.conf.js:7
> 
> Error: Cannot find module 'test-runner-config'
> 	at wallaby-client.js:1

Here is the output of the files from getWallaby.

I think the tests, is not ignoring anything.

```
{ files: 
   [ { pattern: '**/sharedFiles.js',
       instrument: false,
       load: false,
       ignore: true },
     { pattern: '**/karma.conf.js',
       instrument: false,
       load: false,
       ignore: true },
     { pattern: '**/*.js',
       instrument: false,
       load: false,
       ignore: true },
     { pattern: '../../../../node_modules/angular/angular.js',
       instrument: false,
       load: true,
       ignore: false },
     { pattern: '../../../../node_modules/angular-mocks/angular-mocks.js',
       instrument: false,
       load: true,
       ignore: false },
     { pattern: '../../../main/javascript/client/**/*.js',
       instrument: true,
       load: true,
       ignore: false } ],
  tests: 
   [ { pattern: '**/*.js',
       instrument: true,
       load: true,
       ignore: false } ] }
```

Heres my new updated file.

```
var nodeModulesPath = '../../../../node_modules/';
var applicationPath = '../../../main/javascript/client/';

module.exports = [
    {
        type: 'ignore',
        files: [
            '**/sharedFiles.js',
            '**/karma.conf.js'
        ]
    },
    {
        type: 'lib',
        files: [
            nodeModulesPath + 'angular/angular.js',
            nodeModulesPath + 'angular-mocks/angular-mocks.js'
        ]
    },
    {
        type: 'src',
        files: [
            applicationPath + '**/*.js'
        ]
    },
    {
        type: 'specs',
        files: [
            '**/*.js'
        ]
    }
];
```

**Comment by fvanwijk** [comment]
Hi @ianjohnspain, thanks for your issue report.

TRC adds the file patterns in order you defined them in sharedFiles.js.
I used the updated config with this script:

```
var testRunnerConfig = require('test-runner-config'),
  files = require('./sharedFiles.js'),
  config = testRunnerConfig.getKarmaFiles(files);
console.log(config);
```

It returns
```
{ files: 
   [ '../../../../node_modules/angular/angular.js',
     '../../../../node_modules/angular-mocks/angular-mocks.js',
     '../../../main/javascript/client/**/*.js',
     '**/*.js' ],
  exclude: [ '**/sharedFiles.js', '**/karma.conf.js' ] }
```
So the libs are listed first, as expected.

When you use this file/exclude patterns manually in Karma, are your tests running correctly?
Do you have a sample repo so that I can take a closer look?

Test patterns are added als 'ignored' to the Wallaby files list, so when you have a broad test pattern, it is usually better to define the test files pattern more specific, ie. **/*.spec.js.

It is also possible to use `!` in the patterns for Karma and Wallaby, so you do not need the `type: 'ignore'` config. It could save you some headaches.
